//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CosmicEmail {
            get {
                return ((string)(this["CosmicEmail"]));
            }
            set {
                this["CosmicEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CosmicPassword {
            get {
                return ((string)(this["CosmicPassword"]));
            }
            set {
                this["CosmicPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportSavePath {
            get {
                return ((string)(this["ExportSavePath"]));
            }
            set {
                this["ExportSavePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ETYE-PC\\SQLEXPRESS;Initial Catalog=\"6B6BBD80FD1798D29B9948E7A24ECA45_" +
            "TYE MYER - FINAL PROJECT 2016\\FINALPROJECT-MASTER\\FINALPROJECT-MASTER\\FINALPROJE" +
            "CT\\DATABASE.MDF\";Integrated Security=True")]
        public string _6B6BBD80FD1798D29B9948E7A24ECA45_TYE_MYER___FINAL_PROJECT_2016_FINALPROJECT_MASTER_FINALPROJECT_MASTER_FINALPROJECT_DATABASE_MDFConnectionString {
            get {
                return ((string)(this["_6B6BBD80FD1798D29B9948E7A24ECA45_TYE_MYER___FINAL_PROJECT_2016_FINALPROJECT_MAST" +
                    "ER_FINALPROJECT_MASTER_FINALPROJECT_DATABASE_MDFConnectionString"]));
            }
        }
    }
}
